<a href="https://colab.research.google.com/github/Bhoomika923/DATA_SCIENCE_NF/blob/main/Module2/homework/DATA_CLEANING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Messy_Employment_India_Dataset.csv to Messy_Employment_India_Dataset.csv

#LOAD AND INSPECT

In [ ]:
df=pd.read_csv("Messy_Employment_India_Dataset.csv")
df.head()
##load and show first 5 rows

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
0,EMPLOYED,25_34,high school,Technology,Urban,NaN,NaN,40700.0,1/1/2023
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,NaN,17500.0,1/2/2023
2,EMPLOYED,25_34,High School,Retail,Delhi,Low,16.0,77600.0,1/3/2023
3,UNEMPLOYED,18-24,Masters,Retail,Urban,Low,30.0,100200.0,1/4/2023
4,NaN,45-54,Diploma,Fintech,Hyderabad,low,9.0,19500.0,1/5/2023

In [ ]:
df.tail()

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
1995,employed,25-34,Ph.D,Finance,Hyderabad,Low,NaN,113000.0,6/18/2028
1996,EMPLOYED,25-34,PhD,Tech,NaN,NaN,22.0,102200.0,6/19/2028
1997,NaN,35 - 44,Masters,Education,NaN,low,NaN,31600.0,6/20/2028
1998,EMPLOYED,25_34,high school,Retail,Mumbai,HIGH,22.0,92500.0,6/21/2028
1999,UNEMPLOYED,25_34,High School,NaN,NaN,moderate,NaN,43300.0,6/22/2028

In [ ]:
df.sample()

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
1655,EMPLOYED,NaN,Ph.D,Retail,NaN,Low,NaN,91200.0,7/14/2027

# DATASET STRUCTURE

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Status                1732 non-null   object
 1   Age Group             1768 non-null   object
 2   Education             1804 non-null   object
 3   Industry              1799 non-null   object
 4   Location              1787 non-null   object
 5   AI Risk               1716 non-null   object
 6   Years of Experience   980 non-null    float64
 7   Monthly Salary (INR)  1613 non-null   float64
 8   Date Recorded         2000 non-null   object
dtypes: float64(2), object(7)
memory usage: 140.8+ KB

In [ ]:
df.describe(include='all')

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
count,1732,1768,1804,1799,1787,1716,980.000000,1613.000000,2000
unique,6,7,9,8,8,6,NaN,NaN,2000
top,Employed,18 to 24,Bachelors,Retail,Delhi,HIGH,NaN,NaN,6/6/2028
freq,302,262,225,429,233,308,NaN,NaN,1
mean,NaN,NaN,NaN,NaN,NaN,NaN,15.244898,76886.360818,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,9.103941,41628.008054,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,5100.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,7.000000,40700.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,16.000000,77200.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,23.000000,112400.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,30.000000,149900.000000,NaN

# HANDLE MISSING VALUES

In [ ]:
df.isnull().sum()

Status                   268
Age Group                232
Education                196
Industry                 201
Location                 213
AI Risk                  284
Years of Experience     1020
Monthly Salary (INR)     387
Date Recorded              0
dtype: int64

In [ ]:
df=df.dropna()
print(df.isnull().sum())

Status                  0
Age Group               0
Education               0
Industry                0
Location                0
AI Risk                 0
Years of Experience     0
Monthly Salary (INR)    0
Date Recorded           0
dtype: int64

# REMOVE DUPLICATE VALUES

In [ ]:
print("Duplicates:",df.duplicated().sum())
df.drop_duplicates()
print("Duplicates after removing:",df.duplicated().sum())

Duplicates: 0
Duplicates after removing: 0

# CORRECT INCONSITENT FORMATTING AND TEXT VALUES

In [ ]:
df.columns = df.columns.str.strip()   #remove extra space from column name
for col in df.select_dtypes(include="object"):   #remove extra space from textvalues
  df[col] = df[col].str.strip()
for col in df.select_dtypes(include="object"):      ##text to titlecase
  df[col] = df[col].str.title()
df.head()

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
1,Employed,18-24,Diploma,Fintech,Rural,Moderate,16.0,17500.0,1/2/2023
2,Employed,25_34,High School,Retail,Delhi,Low,16.0,77600.0,1/3/2023
3,Unemployed,18-24,Masters,Retail,Urban,Low,30.0,100200.0,1/4/2023
5,Unemployed,25_34,Phd,Tech,Bangalore,High,16.0,54500.0,1/6/2023
11,Unemployed,45-54,High School,Technology,Delhi,High,16.0,27000.0,1/12/2023

In [ ]:
print(df.dtypes)
df["Years of Experience"] = df["Years of Experience"].astype(int)

Status                   object
Age Group                object
Education                object
Industry                 object
Location                 object
AI Risk                  object
Years of Experience       int64
Monthly Salary (INR)    float64
Date Recorded            object
dtype: object

In [ ]:
print(df.dtypes)
# Convert age column if present

if 'Age' in df.columns:
    df['Age'] = pd.to_numeric(df['Age'], errors='coerce')

# Convert salary column if present

if 'Salary' in df.columns:
    df['Salary'] = pd.to_numeric(df['Salary'], errors='coerce')

# Check updated types
print(df.dtypes)

Status                   object
Age Group                object
Education                object
Industry                 object
Location                 object
AI Risk                  object
Years of Experience       int64
Monthly Salary (INR)    float64
Date Recorded            object
dtype: object
Status                   object
Age Group                object
Education                object
Industry                 object
Location                 object
AI Risk                  object
Years of Experience       int64
Monthly Salary (INR)    float64
Date Recorded            object
dtype: object

# STANDARDIZE COLUMN NAMES

In [ ]:
# Convert column names to lowercase

df.columns = df.columns.str.lower()

# Replace spaces with underscores

df.columns = df.columns.str.replace(' ', '_')

# Remove special characters

df.columns = df.columns.str.replace('[^a-zA-Z0-9_]', '', regex=True)

print("Updated Column Names:")
print(df.columns)

Updated Column Names:
Index(['status', 'age_group', 'education', 'industry', 'location', 'ai_risk',
       'years_of_experience', 'monthly_salary_inr', 'date_recorded'],
      dtype='object')

# VALIDATE AND VERIFY

In [ ]:
print("Dataset Shape:")
print(df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nData Types:")
print(df.dtypes)

print("\nPreview of Cleaned Dataset:")
df.head()

Dataset Shape:
(946, 9)

Missing Values:
status                 0
age_group              0
education              0
industry               0
location               0
ai_risk                0
years_of_experience    0
monthly_salary_inr     0
date_recorded          0
dtype: int64

Duplicate Rows:
0

Data Types:
status                  object
age_group               object
education               object
industry                object
location                object
ai_risk                 object
years_of_experience      int64
monthly_salary_inr     float64
date_recorded           object
dtype: object

Preview of Cleaned Dataset:

,status,age_group,education,industry,location,ai_risk,years_of_experience,monthly_salary_inr,date_recorded
1,Employed,18-24,Diploma,Fintech,Rural,Moderate,16,17500.0,1/2/2023
2,Employed,25_34,High School,Retail,Delhi,Low,16,77600.0,1/3/2023
3,Unemployed,18-24,Masters,Retail,Urban,Low,30,100200.0,1/4/2023
5,Unemployed,25_34,Phd,Tech,Bangalore,High,16,54500.0,1/6/2023
11,Unemployed,45-54,High School,Technology,Delhi,High,16,27000.0,1/12/2023

# EXPORT

In [ ]:
df.to_csv("cleaned_dataset.csv", index=False)
print("dataset export success")

dataset export success

In [ ]:
from google.colab import files
files.download("cleaned_dataset.csv")